# Generated by Django 5.0.2 on 2024-03-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_roleuser_club'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roleuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='roleuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='roleuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='roleuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='roleuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='roleuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='roleuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='roleuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='roleuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='roleuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='roleuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
