# Generated by Django 5.0.2 on 2024-03-08 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_org_gov', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='article',
        ),
        migrations.RemoveField(
            model_name='roleuser',
            name='club',
        ),
        migrations.RemoveField(
            model_name='constitution',
            name='club',
        ),
        migrations.RemoveField(
            model_name='roleuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='roleuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='Constitution',
        ),
        migrations.DeleteModel(
            name='RoleUser',
        ),
    ]
