# Generated by Django 5.0.2 on 2024-04-18 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_article_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default=None, max_length=200, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.CharField(default=None, max_length=10000, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
